#!/bin/bash
#Script pur la validation des fichiers

directory=../Àtraiter
fichiers=$(ls $directory)

for fichier in $fichiers
do
	echo "$fichier"
	auteur=$(grep -E "^\".{5,}\S.*\"\s<.*@.*\S.*\.(com|ca|org|us)>$" $directory/$fichier)
	echo "$auteur"
	date=$(grep -E "^(Mon|Tue|Wed|Thu|Fri|Sat|Sun),\s([0-9]\s|1[0-9]\s|2[0-9]\s|3[0-1]\s)(Jul|Aug|Sep|Oct|Nov|Dec|Jan|Feb|Mar|Apr|May|Jun)\s(201[89])\s([0-2][0-9]:[0-5][0-9]:[0-5][0-9])$" $directory/$fichier)
	echo "$date"
done 


