#!/bin/bash
#Script pur la validation des fichiers

directoryATraiter=../Àtraiter
directoryTraites=../Traités
directoryInvalides=../Invalides

fichiers=$(ls $directoryATraiter)


regexNomCourriel="\"(\w|\s)*\"\s<\w*@\w*\.com>"
regexDate="(Mon|Tue|Wed|Thu|Fri|Sat|Sun),\s([0-9]\s|1[0-9]\s|2[0-9]\s|3[0-1]\s)(Jul|Aug|Sep|Oct|Nov|Dec|Jan|Feb|Mar|Apr|May|Jun)\s(201[89])\s(([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])"
regexSujet="(\w|\s){3,20}"
regexMessage=".*\S.*"

formatValid="\e[92m%-22s%s\e[39m\n"
formatInvalid="\e[31m%-22s%s\e[39m\n"
dt=$(date '+%Y-%m-%d %H:%M')




function EffectuerVerification
{
	if [[ $1 =~ $2 ]]
		then
			printf "$formatValid" $3 "Valide"
			return 1
		else
			printf "$formatInvalid" $3  "Invalide"
			return 0
	fi
}

function VerifierValeurRetour
{
	if [ $1 -eq 0 ]
		then
		isValid=$?
	fi
}

function GenererNomFichier
{
	compteur=1
	fileName=$(date '+%Y%m%d%H%M')
	fileExtension="_${compteur}.eml"
	
	while [ -e $1/$fileName$fileExtension ]
	do 
		compteur=$((compteur+1))
		fileExtension="_${compteur}.eml"
	done
	
	nomFichier="${fileName}${fileExtension}"
}

function VerifierFichierExiste
{
	if [ ! -d $1 ]
		then
		$(mkdir $1)
	fi
}

function GenererNomPourDossier
{
	nom=$(echo "$auteur" | egrep -o "^\"(\w|\s)*\"")
	nom=${nom//' '/_}
	nomLenght=$(( ${#nom} - 2 ))
	nom=${nom:1:nomLenght}
}

function GenererCompaniePourDossier
{
	company=$(echo "$auteur" | egrep -o "<\w*@\w*\.com>")
	companyLenght=$(( ${#company} - 2 ))
	company=${company:1:companyLenght}
}

function AjouterLogValide
{
	logValide="[$dt] $1/$2/$3 : $1 -> $4 OK" 
	echo "$logValide" > ../courriels.log
}

function AjouterLogInvalide
{
	logInvalide"[$dt] invalide/$1 : INVALIDE"
	echo "$logInvalide"  > ../courriels.log
}

for fichier in $fichiers
do
	echo -e "\e[96m\n~~~~~~~~$fichier~~~~~~~~\e[39m";
	
	isValid=1
	auteur=$(cut -f1 -d ';' $directoryATraiter/$fichier)
	EffectuerVerification "$auteur" "$regexNomCourriel" "Auteur"
	VerifierValeurRetour $?
	
	date=$(cut -f2 -d ';' $directoryATraiter/$fichier)
	EffectuerVerification "$date" "$regexDate" "Date"
	VerifierValeurRetour $?
	
	sujet=$(cut -f3 -d ';' $directoryATraiter/$fichier)
	EffectuerVerification "$sujet" "$regexSujet" "Sujet"
	VerifierValeurRetour $?
	
	destinataire=$(cut -f4 -d ';' $directoryATraiter/$fichier)
	EffectuerVerification "$destinataire" "$regexNomCourriel" "Destinataire"
	VerifierValeurRetour $?
	
	message=$(cut -f5 -d ';' $directoryATraiter/$fichier)
	EffectuerVerification "$message" "$regexMessage" "Message"
	VerifierValeurRetour $?
	
	if [ $isValid -eq 0 ]
		then
			nomFichier=
			GenererNomFichier $directoryInvalides	
			$(mv $directoryATraiter/$fichier $directoryInvalides/$nomFichier)

			AjouterLogInvalide $nomFichier
		else 
			courrielDestinataire=$
			
			company=
			VerifierFichierExiste $directoryTraites/$company
			
			nom=
			GenererNomPourDossier
			VerifierFichierExiste $directoryTraites/$company/$nom
			
			nomFichier=
			GenererNomFichier  $directoryTraites/$company/$nom 
			$(mv $directoryATraiter/$fichier $directoryTraites/$company/$nom/$nomFichier)

			AjouterLogValide $nom $nomFichier $auteur $destinataire
		      	
	fi
	
	echo -e "\e[96m////////////////////////////\e[39m";
done
